name: Deploy to cloudtype
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Connect deploy key
        uses: cloudtype-github-actions/connect@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          ghtoken: ${{ secrets.GHP_TOKEN }}
      - name: Deploy
        uses: cloudtype-github-actions/deploy@v1
        with:
          token: ${{ secrets.CLOUDTYPE_TOKEN }}
          project: rmjhg/cleanguild
          stage: main
          yaml: |
            name: localhost
            app: next.js
            options:
              nodeversion: "20"
              buildtype: standalone
              install: npm i
              build: npm run build
              env:
                - name: NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN
                  secret: NEXT_PUBLIC_FIRBASE_AUTH_DOMAIN
                - name: NEXT_PUBLIC_FIREBASE_PROJECT_ID
                  secret: NEXT_PUBLIC_FIRBASE_PROJECT_ID
                - name: NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET
                  secret: NEXT_PUBLIC_FIRBASE_STORAGE_BUCKET
                - name: NEXT_PUBLIC_FIREBASE_AUTH_SECRET
                  secret: NEXT_PUBLIC_FIRBASE_AUTH_SECRET
                - name: NEXT_PUBLIC_FIREBASE_API_KEY
                  secret: NEXT_PUBLIC_FIRBASE_API_KEY
                - name: NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
                  secret: NEXT_PUBLIC_FIRBASE_MESSAGING_SENDER_ID
                - name: NEXT_PUBLIC_FIREBASE_APP_ID
                  secret: NEXT_PUBLIC_FIRBASE_APP_ID
                - name: AUTH_SECRET
                  secret: AUTH_SECRET
                - name: AUTH_KAKAO_ID
                  secret: AUTH_KAKAO_ID
                - name: AUTH_KAKAO_SECRET
                  secret: AUTH_KAKAO_SECRET
                - name: NEXT_PUBLIC_API_KEY
                  secret: NEXT_PUBLIC_API_KEY
                - name: NEXTAUTH_URL
                  value: http://cleanguild.kr
              buildenv: []
            context:
              git:
                url: git@github.com:${{ github.repository }}.git
                ref: ${{ github.ref }}
              preset: next.js
