name: CI/CD Pipeline

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때마다 실행
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.12' # 원하는 Node.js 버전으로 변경

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build # 빌드 스크립트에 맞게 수정

      - name: Add SSH host key
        run: |
          ssh-keyscan -p 2020 $SERVER_IP >> ~/.ssh/known_hosts

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # 비밀 키 설정
          SERVER_IP: ${{ secrets.SERVER_IP }} # 서버 IP 설정
          USERNAME: ${{ secrets.USERNAME }} # 사용자 이름 설정
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh -i private_key -p 2020 $USERNAME@$SERVER_IP << 'EOF'
            cd /home/jhg990508/cleanguild # 애플리케이션 경로로 변경
            git pull origin main
            npm install
            npm run build
            pm2 restart cleanguild  # PM2로 재시작할 애플리케이션 이름
          EOF
