name: CI/CD Pipeline

on:
  push:
    branches:
      - main # main 브랜치에 푸시될 때마다 실행
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.11' # 원하는 Node.js 버전으로 변경

      - name: Install dependencies
        run: npm install

      - name: Build the application
        run: npm run build # 빌드 스크립트에 맞게 수정

      - name: Deploy to server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # 비밀 키 설정
          SERVER_IP: ${{ secrets.SERVER_IP }} # 서버 IP 설정
          USERNAME: ${{ secrets.USERNAME }} # 사용자 이름 설정
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          ssh -i private_key -p 2020 -o StrictHostKeyChecking=no $USERNAME@$SERVER_IP << 'EOF'
            cd /home/jhg990508/cleanGuild # 애플리케이션 경로로 변경
            git pull origin main
            npm install
            npm run build

            # .env.local 파일에 변수를 추가

            echo "AUTH_SECRET="${{ secrets.AUTH_SECRET }} > .env.local
            echo "AUTH_KAKAO_ID="${{ secrets.AUTH_KAKAO_ID }} >> .env.local
            echo "AUTH_KAKAO_SECRET="${{ secrets.AUTH_KAKAO_SECRET }} >> .env.local
            echo "AUTH_KAKAO_STATE="${{ secrets.AUTH_KAKAO_STATE }} >> .env.local
            echo "AUTH_KAKAO_LOGOUT_REDIRECT_URI="${{ secrets.AUTH_KAKAO_LOGOUT_REDIRECT_URI }} >> .env.local
            echo "NEXT_PUBLIC_API_KEY="${{ secrets.NEXT_PUBLIC_API_KEY }} >> .env.local
            echo "NEXTAUTH_URL="${{ secrets.NEXTAUTH_URL }} >> .env.local

            echo "NEXT_PUBLIC_FETCH_URL="${{ secrets.NEXT_PUBLIC_FETCH_URL }} >> .env.local
            echo "NEXT_PUBLIC_BACKEND_URL="${{ secrets.NEXT_PUBLIC_BACKEND_URL }} >> .env.local
            echo "NEXT_PUBLIC_MONGODB_URI="${{ secrets.NEXT_PUBLIC_MONGODB_URI }} >> .env.local

            echo "NEXT_PUBLIC_AUTH_KAKAO_ID="${{ secrets.NEXT_PUBLIC_AUTH_KAKAO_ID }} >> .env.local
            echo "NEXT_PUBLIC_AUTH_KAKAO_SECRET="${{ secrets.NEXT_PUBLIC_AUTH_KAKAO_SECRET }} >> .env.local
            echo "NEXT_PUBLIC_AUTH_KAKAO_STATE="${{ secrets.NEXT_PUBLIC_AUTH_KAKAO_STATE }} >> .env.local
            echo "HELLOWORLD"="hello" >> .env.local



            pm2 restart nextjs-app  # PM2로 재시작할 애플리케이션 이름
          EOF
