name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.12' # 원하는 Node.js 버전으로 변경

      - name: Install dependencies
        run: |
          if ! npm install; then
            echo "Failed to install dependencies"
            exit 1
          fi

      - name: Build the application
        run: |
          if ! npm run build; then
            echo "Failed to build application"
            exit 1
          fi

      - name: Setup SSH
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -p 2020 -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to server
        env:
          SERVER_IP: ${{ secrets.SERVER_IP }}
          USERNAME: ${{ secrets.USERNAME }}
        run: |
          ssh -i ~/.ssh/deploy_key -p 2020 $USERNAME@$SERVER_IP << 'EOF'
            set -e  # 에러 발생 시 스크립트 중단

            echo "Starting deployment..."
            
            # 애플리케이션 디렉토리로 이동
            cd /home/jhg990508/cleanguild || exit 1
            
            # Git pull
            if ! git pull origin main; then
              echo "Git pull failed"
              exit 1
            fi

            # 의존성 설치
            if ! npm install; then
              echo "npm install failed"
              exit 1
            fi

            # 빌드
            if ! npm run build; then
              echo "Build failed"
              exit 1
            fi

            # 환경 변수 설정
            cat > .env.local << EOL
AUTH_SECRET="${{ secrets.AUTH_SECRET }}"
AUTH_KAKAO_ID="${{ secrets.AUTH_KAKAO_ID }}"
AUTH_KAKAO_SECRET="${{ secrets.AUTH_KAKAO_SECRET }}"
AUTH_KAKAO_STATE="${{ secrets.AUTH_KAKAO_STATE }}"
AUTH_KAKAO_LOGOUT_REDIRECT_URI="${{ secrets.AUTH_KAKAO_LOGOUT_REDIRECT_URI }}"
NEXT_PUBLIC_API_KEY="${{ secrets.NEXT_PUBLIC_API_KEY }}"
NEXTAUTH_URL="${{ secrets.NEXTAUTH_URL }}"
NEXT_PUBLIC_FETCH_URL="${{ secrets.NEXT_PUBLIC_FETCH_URL }}"
NEXT_PUBLIC_BACKEND_URL="${{ secrets.NEXT_PUBLIC_BACKEND_URL }}"
NEXT_PUBLIC_MONGODB_URI="${{ secrets.NEXT_PUBLIC_MONGODB_URI }}"
NEXT_PUBLIC_AUTH_KAKAO_ID="${{ secrets.NEXT_PUBLIC_AUTH_KAKAO_ID }}"
NEXT_PUBLIC_AUTH_KAKAO_SECRET="${{ secrets.NEXT_PUBLIC_AUTH_KAKAO_SECRET }}"
NEXT_PUBLIC_AUTH_KAKAO_STATE="${{ secrets.NEXT_PUBLIC_AUTH_KAKAO_STATE }}"
EOL

            # PM2 재시작 및 상태 확인
            if ! pm2 restart cleanguild; then
              echo "Failed to restart PM2 process"
              exit 1
            fi

            # PM2 상태 확인
            if ! pm2 status cleanguild | grep -q "online"; then
              echo "PM2 process is not running"
              exit 1
            fi

            echo "Deployment completed successfully"
          EOF
